---
hallway_entrance_mean: 0.8 # range: 0.1-1.0
kitchen_area: 20 # range: 1 - 1000
bedroom_area: 40 # range: 1 - 1000
living_room_area: 52 # range: 1 - 1000 (1.3 times larger than bedrooms)
dining_room_area: 20 # range: 1 - 1000
bathroom_area: 8 # range: 1 - 1000
aspect_ratio: 50.0 # range: 10-2000
convexity: 5.0
wall_simplicity: 1.0 # range: 1-2000
bedroom_count: 2 # range: 1-3
public_bathroom_via_hallway_count: 1 # range: 1-3
public_bathroom_via_living_room_count: 1 # range: 1-3