seed: 42
device: "cuda"  # or "cpu"
output_dir: "outputs"
epochs: 2
batch_size: 8
learning_rate: 1e-3
num_workers: 2

dataset:
  name: "synthetic"
  num_samples: 256
  image_size: 128
  vocab_size: 512
  max_text_len: 16
  proprio_dim: 7
  tactile_dim: 4
  action_dim: 7

model:
  config: "configs/model_moe.yaml"

log_interval: 10
save_interval: 1
