model:
  name: ActionChunkPredictor
  d_model: 256
  levels: 1
  use_vq: true
  codebook_size: 128
  boundary_threshold: 0.5
encoder:
  type: transformer
  depth: 4
  heads: 4
  dropout: 0.1
training:
  batch_size: 16
  epochs: 10
  lr: 3.0e-4
  log_interval: 20
data:
  train: data/processed/train_sequences.pt
  val:   data/processed/train_sequences.pt
