from setuptools import setup, find_packages

setup(
    name="vla-moe-manipulation",
    version="0.1.0",
    description="Mixture-of-Experts Vision-Language-Action Model for Robotic Manipulation",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/your-org/VLA-MoE-Manipulation",
    license="Apache License 2.0",
    packages=find_packages(exclude=("tests", "docs")),
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.2.0",
        "torchvision>=0.17.0",
        "torchaudio>=2.2.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "Pillow>=10.0.0",
        "scikit-learn>=1.3.0",
        "transformers>=4.40.0",
        "sentencepiece>=0.2.0",
        "matplotlib>=3.8.0",
        "seaborn>=0.13.0",
        "opencv-python>=4.9.0",
        "pyyaml>=6.0.1",
        "tqdm>=4.66.0",
        "einops>=0.7.0",
    ],
    extras_require={
        "dev": ["black>=24.0.0", "flake8>=7.0.0", "jupyterlab>=4.0.0"],
        "logging": ["tensorboard>=2.16.0", "wandb>=0.16.0"],
    },
    entry_points={
        "console_scripts": [
            "vlamoe-train=training.train:main",
            "vlamoe-infer=inference.run_inference:main",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords="vision-language-action mixture-of-experts robotics manipulation",
)
