name: household_room
floor:
  type: plane
  material: wood
objects:
  - name: sofa
    type: rigid
    asset: usd://furniture/sofa.usd
    pose: [1.0, 0.0, 0.0, 0, 0, 0, 1]
    physical: { mass: 20.0, friction: 0.7 }
  - name: table
    type: rigid
    asset: usd://furniture/table.usd
    pose: [0.4, 0.3, 0.0, 0, 0, 0, 1]
    physical: { mass: 10.0, friction: 0.6 }
  - name: book
    type: rigid
    asset: usd://props/book.usd
    pose: [0.42, 0.32, 0.75, 0, 0, 0, 1]
    physical: { mass: 0.3, friction: 0.5 }
robots:
  - name: mobile_base
    type: mobile
    asset: usd://robots/mobile_base.usd
    base_pose: [-1.0, -0.5, 0.0, 0, 0, 0, 1]
goals:
  - type: navigate
    target_pose: [0.2, -0.2, 0.0, 0, 0, 0, 1]
